<?php
/**
 * MagePrince
 * Copyright (C) 2020 Mageprince <info@mageprince.com>
 *
 * @package Mageprince_Faq
 * @copyright Copyright (c) 2020 Mageprince (http://www.mageprince.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author MagePrince <info@mageprince.com>
 */
?>
<?php
$isEnable = $block->getConfig('faqtab/general/enable');
$showGroup = $block->getConfig('faqtab/design/showgroup');
$showGroupTitle = $block->getConfig('faqtab/design/showgrouptitle');
$pageType = $block->getConfig('faqtab/design/page_type');
$faqGroupCollection = $block->getFaqGroupCollection();
?>
<?php if ($faqGroupCollection->getSize()) : ?>
    <?php if ($isEnable) : ?>
    <div class="faq-collection">
        <?php if ($showGroup || $pageType == 'ajax') : ?>
            <div class="faq-groups">
                <?php foreach ($faqGroupCollection as $group) : ?>
                    <div class="faq-group">
                        <?php if ($showGroup || $pageType == 'ajax') : ?>
                            <div id="faq-group-image" class="faq-group-image">
                                <a href="#group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>" class="group-link" groupId="<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                                <?php if ($group->getIcon()) : ?>
                                    <img class="group-image"
                                         src="<?php /* @noEscape */ echo $block->getImageUrl($group->getIcon()); ?>" />
                                <?php else : ?>
                                    <img class="group-image"
                                         src="<?php /* @noEscape */ echo $block->getViewFileUrl('Mageprince_Faq::images/faq.png'); ?>" />
                                <?php endif; ?>
                                </a>
                            </div>
                        <?php endif; ?>
                        <?php if ($showGroupTitle) : ?>
                            <div class="faq-groupname">
                                <a href="#group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>" class="group-link" groupId="<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                                    <?php /* @noEscape */ echo $group->getGroupName(); ?>
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <div id="faq-content" class="faq-content">
            <?php if ($pageType == 'scroll') : ?>
                <?php foreach ($faqGroupCollection as $group) : ?>
                    <div id="group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                        <?php if ($showGroupTitle) : ?>
                            <div class="group-title">
                                <i></i><?php /* @noEscape */ echo $group->getGroupName(); ?>
                            </div>
                        <?php endif; ?>
                        <div class="faq-accordion">
                        <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
                            <?php if ($faqCollection->getSize()) : ?>
                                <?php foreach ($faqCollection as $faq) : ?>
                                    <h3><?php /* @noEscape */ echo $faq->getTitle(); ?></h3>
                                    <div>
                                        <p><?php /* @noEscape */ echo $block->filterOutputHtml($faq->getContent()); ?></p>
                                    </div>
                                <?php endforeach; ?>
                            <?php else : ?>
                                <div><?php /* @noEscape */ echo __('No FAQ available'); ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else :?>
                <?php $group = $faqGroupCollection->getFirstItem(); ?>
                <?php if ($showGroupTitle) : ?>
                    <div class="group-title" id="group<?php /* @noEscape */ echo $group->getFaqgroupId(); ?>">
                        <i></i><?php /* @noEscape */ echo $group->getGroupName(); ?>
                    </div>
                <?php endif; ?>
                <div class="faq-accordion">
                    <?php $faqCollection = $block->getFaqCollection($group->getId()); ?>
                    <?php if ($faqCollection->getSize()) : ?>
                        <?php foreach ($faqCollection as $faq) : ?>
                            <h3><?php /* @noEscape */ echo $faq->getTitle(); ?></h3>
                            <div>
                                <p><?php /* @noEscape */ echo $block->filterOutputHtml($faq->getContent()); ?></p>
                            </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <div><?php /* @noEscape */ echo __('No FAQ available'); ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
<?php else : ?>
    <div>
        <h1><?php /* @noEscape */ echo __('No FAQ Group available'); ?></h1>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "faq": {
                "pageType" : "<?= $pageType ?>",
                "ajax_url" : "<?= $block->getBaseUrl() ?>"
            }
        }
    }
</script>
