<?php $isEnable = $block->getConfig('faqtab/general/enable') ?>
<?php $showGroup = $block->getConfig('faqtab/faqgroup/showgroup') ?>
<?php $faqGroupCollection = $block->getFaqGroupCollection() ?>
<?php if($isEnable): ?>
    <?php if ($showGroup): ?>
        <div class="faq-groups">
            <?php foreach ($faqGroupCollection as $group): ?>
                <div class="faq-group">
                    <a href="#group<?php echo $group->getFaqgroupId() ?>" class="group-link">
                    <?php if ($group->getIcon()): ?>
                        <img class="group-image" src="<?php echo $block->getImageUrl($group->getIcon()) ?>" />
                    <?php else: ?>
                        <img class="group-image" src="<?php echo $block->getViewFileUrl('Prince_Faq::images/faq.png')?>" />
                    <?php endif; ?>
                    <div class="faq-groupname"><?php echo $group->getGroupName() ?></div>
                    </a>
                </div>    
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <div class="faq-content">
    <?php foreach($faqGroupCollection as $group): ?>

        <div class="group-title" id="group<?php echo $group->getFaqgroupId() ?>">
        <i></i><?php echo $group->getGroupName() ?>
        </div>
        
        <div class="faq-accordion">
        <?php $faqCollection = $this->getFaqCollection($group->getId()) ?>
            <?php foreach($faqCollection as $faq): ?> 
                <h3><?php echo $faq->getTitle() ?></h3>
                <div>
                    <p><?php echo $block->filterOutputHtml($faq->getContent()) ?></p>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
    </div>

    <script type="text/x-magento-init">
       {
            "*": {
                "faqjs": {
                    "animateSpeed": "<?php echo $block->getConfig('faqtab/faq/animation') ?>",
                    "defaultActive": "<?php echo $block->getConfig('faqtab/general/active') ?>"
                }
            }
        }
    </script>
<?php endif; ?>

<style type="text/css">
.ui-accordion .ui-state-default:after{

content: '\e608';
font-family: 'luma-icons';
float: right;
}

.ui-accordion .ui-accordion-header-active:after{
    content: '\e622';
    font-family: 'luma-icons';
}

</style>